// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/images": {
            "get": {
                "description": "Get all image filenames from the static directory.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "images"
                ],
                "summary": "List all images",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Unable to read directory",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/images/{filename}": {
            "get": {
                "description": "Serve image by filename, with optional resizing (w, h, fit, auto=format)",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "images"
                ],
                "summary": "Get image file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Image file name",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Width",
                        "name": "w",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Height",
                        "name": "h",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fit mode (crop)",
                        "name": "fit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Auto format (format)",
                        "name": "auto",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "File name required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Image not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an image file from the static directory by its filename.",
                "tags": [
                    "images"
                ],
                "summary": "Delete an image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Image file name",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "File name required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Image not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to delete file",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restart": {
            "get": {
                "description": "Stops and restarts the feh slideshow viewer.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "feh"
                ],
                "summary": "Restart the feh slideshow",
                "responses": {
                    "200": {
                        "description": "feh restarted.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/start": {
            "get": {
                "description": "Launches the feh slideshow viewer on the configured uploads directory.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "feh"
                ],
                "summary": "Start the feh slideshow",
                "responses": {
                    "200": {
                        "description": "feh started.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/stop": {
            "get": {
                "description": "Stops the running feh process if active.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "feh"
                ],
                "summary": "Stop the feh slideshow",
                "responses": {
                    "200": {
                        "description": "feh stopped.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "Upload an image file via multipart form data.",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "upload"
                ],
                "summary": "Upload image",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Image file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "File uploaded successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing file",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "405": {
                        "description": "Invalid request method",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
